/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Tony
 */
import java.awt.event.KeyEvent;
import java.sql.*;
import javax.swing.*;
import net.proteanit.sql.DbUtils;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.text.*;
import java.util.logging.Level;
import java.util.logging.Logger;

public class Club_Member extends javax.swing.JFrame {
    Connection conn=null;
    ResultSet rs =null;
    PreparedStatement pst= null;
    /**
     * Creates new form Club_Member
     */
    public Club_Member() {
        initComponents();
        conn=javaconnect.ConnectDB();
        Update_table();
        CurrentDate();
        ComboSelect();
        ComboSelect2();
        

    }
    
    public void ComboSelect(){
    int c= cmd_Combobox.getSelectedIndex();
        if(c==1){
            Employee_info s =new Employee_info();
            s.setVisible(true);
        
        }
        if(c==2){            
            Prior_Member p =new Prior_Member();
            p.setVisible(true);    
    
        }   /********REMEMBER to change the INDEX NUMBERS for item in combo box.***** and change letter variable ex. "s" "p" etc.*/
        if(c==3){
            Documents d =new Documents();
            d.setVisible(true);
        
        }
    }
    public void ComboSelect2(){
        try{
            String sql ="Select * from `fitness247`.`club members`";
            pst=conn.prepareStatement (sql);
            rs=pst.executeQuery();
            while(rs.next()){
            String billingType =rs.getString("Billing Type");
            cmd_Combobox2.addItem(billingType);
            }             
             
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        
        }finally{
        try{
            rs.close();
            pst.close();
            //conn.close();
               
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
               
        }
     
        
    }
    public void CurrentDate(){
        
        Thread clock=new Thread(){
        public void run (){
            for(;;){
                Calendar cal= new GregorianCalendar();
                int month= cal.get(Calendar.MONTH);
                int year= cal.get(Calendar.YEAR);
                int day= cal.get(Calendar.DAY_OF_MONTH);
                date_txt.setText("DATE "+(month+1)+"/"+day+"/"+year);
        
                int second= cal.get(Calendar.SECOND);
                int minute= cal.get(Calendar.MINUTE);
                int hour= cal.get(Calendar.HOUR);
                time_txt.setText("TIME "+hour+":"+(minute)+":"+second);
                try {               
                    sleep(1000);
                } catch (InterruptedException ex) {
                    Logger.getLogger(Club_Member.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                
            
            }
        
        }
        
        
        };
        clock.start();
    }
private void Update_table(){
    try{
    String sql ="Select * from `fitness247`.`club members`";
    pst=conn.prepareStatement (sql);
    rs=pst.executeQuery();
    Table_ClubMembers.setModel(DbUtils.resultSetToTableModel(rs));
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
    }finally{
        try{
            rs.close();
            pst.close();
            //conn.close();
               
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        
        }
               
        }
   
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem3 = new javax.swing.JMenuItem();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        txt_search = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        cmd_Combobox = new javax.swing.JComboBox();
        jPanel7 = new javax.swing.JPanel();
        cmd_print = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        txt_count = new javax.swing.JTextField();
        cmd_Calculate = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        cmd_SortBillingType = new javax.swing.JRadioButton();
        cmd_SortLastName = new javax.swing.JRadioButton();
        jPanel10 = new javax.swing.JPanel();
        cmd_UpdateTable = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Table_ClubMembers = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        cmd_save = new javax.swing.JButton();
        cmd_delete = new javax.swing.JButton();
        cmd_clear = new javax.swing.JButton();
        cmd_update = new javax.swing.JButton();
        cmd_exit = new javax.swing.JButton();
        cmd_openWeb = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txt_Date = new com.toedter.calendar.JDateChooser();
        cmd_Combobox2 = new javax.swing.JComboBox();
        txt_billingtype = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem5 = new javax.swing.JMenuItem();
        date_txt = new javax.swing.JMenu();
        time_txt = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 103, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 45, Short.MAX_VALUE)
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Club Member Table", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(0, 0, 255))); // NOI18N

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(0, 0, 255))); // NOI18N

        txt_search.setBackground(new java.awt.Color(255, 255, 0));
        txt_search.setToolTipText("Search Club Members by Last Name, First Name\n or Access Key Number");
        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_searchKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Additional Tables", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(0, 0, 255))); // NOI18N

        cmd_Combobox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmd_Combobox.setForeground(new java.awt.Color(0, 102, 153));
        cmd_Combobox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Club Member Table", "Database User", "Prior Members", "Documents" }));
        cmd_Combobox.setToolTipText("Opens Additional Tables");
        cmd_Combobox.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cmd_ComboboxPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(cmd_Combobox, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmd_Combobox, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Print Member List", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(0, 0, 255))); // NOI18N

        cmd_print.setBackground(new java.awt.Color(255, 51, 51));
        cmd_print.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmd_print.setForeground(new java.awt.Color(0, 102, 153));
        cmd_print.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Actions-document-print-icon.png"))); // NOI18N
        cmd_print.setText("Print");
        cmd_print.setToolTipText("Prints the Club Member list from the Database");
        cmd_print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_printActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmd_print)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmd_print)
                .addContainerGap())
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Number of Members", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(0, 0, 255))); // NOI18N

        cmd_Calculate.setBackground(new java.awt.Color(255, 51, 51));
        cmd_Calculate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmd_Calculate.setForeground(new java.awt.Color(0, 102, 153));
        cmd_Calculate.setText("Calculate");
        cmd_Calculate.setToolTipText("Calculates the Number of Members");
        cmd_Calculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_CalculateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmd_Calculate)
                .addGap(18, 18, 18)
                .addComponent(txt_count, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 46, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_count, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmd_Calculate))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Table Sort Order", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(0, 0, 255))); // NOI18N

        buttonGroup1.add(cmd_SortBillingType);
        cmd_SortBillingType.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmd_SortBillingType.setForeground(new java.awt.Color(0, 102, 153));
        cmd_SortBillingType.setText("Billing Type");
        cmd_SortBillingType.setToolTipText("Sorts the Table by Billing Type");
        cmd_SortBillingType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_SortBillingTypeActionPerformed(evt);
            }
        });

        buttonGroup1.add(cmd_SortLastName);
        cmd_SortLastName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmd_SortLastName.setForeground(new java.awt.Color(0, 102, 153));
        cmd_SortLastName.setText("Last Name");
        cmd_SortLastName.setToolTipText("Sorts the Table by Last Name");
        cmd_SortLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_SortLastNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmd_SortLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cmd_SortBillingType, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmd_SortLastName)
                    .addComponent(cmd_SortBillingType))
                .addGap(47, 47, 47))
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Refresh Table", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(0, 0, 255))); // NOI18N

        cmd_UpdateTable.setBackground(new java.awt.Color(255, 51, 51));
        cmd_UpdateTable.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmd_UpdateTable.setForeground(new java.awt.Color(0, 102, 153));
        cmd_UpdateTable.setText("Refresh");
        cmd_UpdateTable.setToolTipText("Refresh the Table View");
        cmd_UpdateTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_UpdateTableActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmd_UpdateTable)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmd_UpdateTable)
                .addContainerGap())
        );

        Table_ClubMembers.setForeground(new java.awt.Color(0, 102, 153));
        Table_ClubMembers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Table_ClubMembers.setToolTipText("Club Member Table");
        Table_ClubMembers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table_ClubMembersMouseClicked(evt);
            }
        });
        Table_ClubMembers.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Table_ClubMembersKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(Table_ClubMembers);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(30, 30, 30))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 85, Short.MAX_VALUE))
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(98, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel3);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Club Member Edit", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(0, 0, 255))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Member ID");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Access Key");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("First Name");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Last Name");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Street Address");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("City");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("State");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Postal Code");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Email");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Home Number");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Work Number");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Mobile Number");

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });

        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField2KeyTyped(evt);
            }
        });

        jTextField8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField8KeyTyped(evt);
            }
        });

        jTextField10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField10KeyTyped(evt);
            }
        });

        jTextField11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField11KeyTyped(evt);
            }
        });

        jTextField12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField12KeyTyped(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buttons", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(0, 0, 255))); // NOI18N

        cmd_save.setBackground(new java.awt.Color(255, 51, 51));
        cmd_save.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmd_save.setForeground(new java.awt.Color(0, 102, 153));
        cmd_save.setText("Save");
        cmd_save.setToolTipText("Saves the New Member Information to  the Database");
        cmd_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_saveActionPerformed(evt);
            }
        });

        cmd_delete.setBackground(new java.awt.Color(255, 51, 51));
        cmd_delete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmd_delete.setForeground(new java.awt.Color(0, 102, 153));
        cmd_delete.setText("Delete");
        cmd_delete.setToolTipText("Deletes the Selected Member from the Database");
        cmd_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_deleteActionPerformed(evt);
            }
        });

        cmd_clear.setBackground(new java.awt.Color(255, 51, 51));
        cmd_clear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmd_clear.setForeground(new java.awt.Color(0, 102, 153));
        cmd_clear.setText("Clear");
        cmd_clear.setToolTipText("Clears the Text Fields");
        cmd_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_clearActionPerformed(evt);
            }
        });

        cmd_update.setBackground(new java.awt.Color(255, 51, 51));
        cmd_update.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmd_update.setForeground(new java.awt.Color(0, 102, 153));
        cmd_update.setText("Update");
        cmd_update.setToolTipText("Updates Member Information in the Database");
        cmd_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_updateActionPerformed(evt);
            }
        });

        cmd_exit.setBackground(new java.awt.Color(255, 51, 51));
        cmd_exit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmd_exit.setForeground(new java.awt.Color(0, 102, 153));
        cmd_exit.setText("Exit");
        cmd_exit.setToolTipText("Exits the Program");
        cmd_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_exitActionPerformed(evt);
            }
        });

        cmd_openWeb.setBackground(new java.awt.Color(255, 51, 51));
        cmd_openWeb.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmd_openWeb.setForeground(new java.awt.Color(0, 102, 153));
        cmd_openWeb.setText("Open Web");
        cmd_openWeb.setToolTipText("Opens a Web Page");
        cmd_openWeb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_openWebActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmd_delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmd_save, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cmd_update)
                        .addGap(18, 18, 18)
                        .addComponent(cmd_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(cmd_openWeb))
                    .addComponent(cmd_clear))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmd_save)
                    .addComponent(cmd_clear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmd_delete)
                    .addComponent(cmd_update)
                    .addComponent(cmd_exit)
                    .addComponent(cmd_openWeb)))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Billing Type");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Date Joined");

        txt_Date.setToolTipText("Year-Month-Day");
        txt_Date.setDateFormatString("yyyy-MM-dd");

        cmd_Combobox2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmd_Combobox2.setForeground(new java.awt.Color(0, 102, 153));
        cmd_Combobox2.setMaximumRowCount(3);
        cmd_Combobox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ACH/Credit", "Paid in Full", "Student" }));
        cmd_Combobox2.setToolTipText("Selects the Billing Type");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5)
                        .addComponent(jLabel6)
                        .addComponent(jLabel7)
                        .addComponent(jLabel8)
                        .addComponent(jLabel9)
                        .addComponent(jLabel10)
                        .addComponent(jLabel11)
                        .addComponent(jLabel12)
                        .addComponent(jLabel13)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(26, 26, 26)))
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField2)
                    .addComponent(jTextField3)
                    .addComponent(jTextField12)
                    .addComponent(jTextField11)
                    .addComponent(jTextField10)
                    .addComponent(jTextField9)
                    .addComponent(jTextField8)
                    .addComponent(jTextField7)
                    .addComponent(jTextField6)
                    .addComponent(jTextField5)
                    .addComponent(jTextField4)
                    .addComponent(jTextField1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txt_Date, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cmd_Combobox2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_billingtype)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                                            .addComponent(jLabel2)
                                                                                                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                        .addGap(18, 18, 18)
                                                                                                        .addComponent(jLabel3))
                                                                                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                .addGap(18, 18, 18)
                                                                                                .addComponent(jLabel4))
                                                                                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                        .addGap(18, 18, 18)
                                                                                        .addComponent(jLabel5))
                                                                                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addGap(18, 18, 18)
                                                                                .addComponent(jLabel6))
                                                                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addGap(18, 18, 18)
                                                                        .addComponent(jLabel7))
                                                                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jLabel8))
                                                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jLabel9))
                                                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel10))
                                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel11))
                                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel12))
                            .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_billingtype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmd_Combobox2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(txt_Date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        jScrollPane3.setViewportView(jPanel1);

        jMenu1.setText("File");
        jMenu1.add(jSeparator1);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem5.setText("Exit");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuBar1.add(jMenu1);

        date_txt.setBackground(new java.awt.Color(255, 255, 0));
        date_txt.setText("Date");
        jMenuBar1.add(date_txt);

        time_txt.setBackground(new java.awt.Color(255, 255, 0));
        time_txt.setText("Time");
        jMenuBar1.add(time_txt);

        jMenu2.setText("Help");
        jMenu2.setToolTipText("Opens the Help File");

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setText("Help File");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1349, 1349, 1349)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setBounds(0, 0, 1323, 889);
    }// </editor-fold>//GEN-END:initComponents

    private void cmd_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_saveActionPerformed
            try {
                String sql = "Insert into `fitness247`.`club members` (`Member ID`,\n" +
            "`Access Key Number`,\n" +
            "`First Name`,\n" +
            "`Last Name`,\n" +
            "`Street Address`,\n" +
            "`City`,\n" +
            "`State`,\n" +
            "`Postal Code`,\n" +
            "`Email`,\n" +
            "`Home Number`,\n" +
            "`Work Number`,\n" +
            "`Mobile Number`,\n"+
            "`Billing Type`,\n"+
            "`Date Joined`) values (?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
            pst=conn.prepareStatement (sql);
            pst.setString(1,jTextField1.getText());
            pst.setString(2,jTextField2.getText());
            pst.setString(3,jTextField3.getText());
            pst.setString(4,jTextField4.getText());
            pst.setString(5,jTextField5.getText());
            pst.setString(6,jTextField6.getText());
            pst.setString(7,jTextField7.getText());
            pst.setString(8,jTextField8.getText());
            pst.setString(9,jTextField9.getText());
            pst.setString(10,jTextField10.getText());
            pst.setString(11,jTextField11.getText());
            pst.setString(12,jTextField12.getText());
            String value= cmd_Combobox2.getSelectedItem().toString();
            pst.setString(13,value);
            pst.setString(14,((JTextField)txt_Date.getDateEditor().getUiComponent()).getText());
                       
                        
            pst.execute();
            
                JOptionPane.showMessageDialog(null, "Saved");
           
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
            try {
                String sql = "Insert into `fitness247`.`prior members` (`Member ID`,\n" +
            "`Access Key Number`,\n" +
            "`First Name`,\n" +
            "`Last Name`,\n" +
            "`Street Address`,\n" +
            "`City`,\n" +
            "`State`,\n" +
            "`Postal Code`,\n" +
            "`Email`,\n" +
            "`Home Number`,\n" +
            "`Work Number`,\n" +
            "`Mobile Number`,\n" +
            "`Billing Type`,\n"+
            "`Date Joined`) values (?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
            pst=conn.prepareStatement (sql);
            pst.setString(1,jTextField1.getText());
            pst.setString(2,jTextField2.getText());
            pst.setString(3,jTextField3.getText());
            pst.setString(4,jTextField4.getText());
            pst.setString(5,jTextField5.getText());
            pst.setString(6,jTextField6.getText());
            pst.setString(7,jTextField7.getText());
            pst.setString(8,jTextField8.getText());
            pst.setString(9,jTextField9.getText());
            pst.setString(10,jTextField10.getText());
            pst.setString(11,jTextField11.getText());
            pst.setString(12,jTextField12.getText());
            String value= cmd_Combobox2.getSelectedItem().toString();
            pst.setString(13,value);
            pst.setString(14,((JTextField)txt_Date.getDateEditor().getUiComponent()).getText());
            
                        
            pst.execute();
            }catch(Exception e) {
            JOptionPane.showMessageDialog(null, e);
        
            }finally{
        try{
            rs.close();
            pst.close();
            //conn.close();
               
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
            Update_table();    
        }

                             

    }//GEN-LAST:event_cmd_saveActionPerformed

    private void cmd_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_clearActionPerformed
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        jTextField7.setText("");
        jTextField8.setText("");
        jTextField9.setText("");
        jTextField10.setText("");
        jTextField11.setText("");
        jTextField12.setText("");
        txt_billingtype.setText("");
        ((JTextField)txt_Date.getDateEditor().getUiComponent()).setText("");
        
        
    }//GEN-LAST:event_cmd_clearActionPerformed

    private void cmd_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_exitActionPerformed
        int p= JOptionPane.showConfirmDialog(null, "Are you sure you want to Exit?","Exit", JOptionPane.YES_NO_OPTION);
        if(p==0){
        System.exit(0);
        }
        
    }//GEN-LAST:event_cmd_exitActionPerformed

    private void Table_ClubMembersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table_ClubMembersMouseClicked
        try{
            int row =Table_ClubMembers.getSelectedRow();
            String Table_click=(Table_ClubMembers.getModel().getValueAt(row, 0).toString());
            String sql = ("select * from `fitness247`.`club members` where `club members`.`Member ID` = '"+Table_click+"' ");
            pst=conn.prepareStatement (sql);
             rs=pst.executeQuery();
            if (rs.next()){
            
            String add1 =rs.getString("Member ID");
            jTextField1.setText(add1);
            String add2 =rs.getString("Access Key Number");
            jTextField2.setText(add2);
            String add3 =rs.getString("First Name");
            jTextField3.setText(add3);
            String add4 =rs.getString("Last Name");
            jTextField4.setText(add4);
            String add5 =rs.getString("Street Address");
            jTextField5.setText(add5);
            String add6 =rs.getString("City");
            jTextField6.setText(add6);
            String add7 =rs.getString("State");
            jTextField7.setText(add7);
            String add8 =rs.getString("Postal Code");
            jTextField8.setText(add8);
            String add9 =rs.getString("Email");
            jTextField9.setText(add9);
            String add10 =rs.getString("Home Number");
            jTextField10.setText(add10);
            String add11 =rs.getString("Work Number");
            jTextField11.setText(add11);
            String add12 =rs.getString("Mobile Number");
            jTextField12.setText(add12);
            String add13 =rs.getString("Billing Type");
            txt_billingtype.setText(add13);
            String add14 =rs.getString("Date Joined");
            ((JTextField)txt_Date.getDateEditor().getUiComponent()).setText(add14);
            /**Can also try: Date add14 =rs.getDate("Date Joined");
             txt_Date.setDate(add14);     The ABOVE Code still is working good*/
            
            } 
        }catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        
              
        
        }finally{
        try{
            rs.close();
            pst.close();
            //conn.close();
               
        }
        catch(Exception e){
            JOptionPane.showMessageDialog (null,e);
        }
               
        }
    }//GEN-LAST:event_Table_ClubMembersMouseClicked

    private void cmd_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_deleteActionPerformed
        int d= JOptionPane.showConfirmDialog(null, "Are you sure you want to Delete?","Delete", JOptionPane.YES_NO_OPTION);
        if(d==0){
        String sql= "delete from `fitness247`.`club members` where `club members`.`Member ID` =? ";
        try{
           pst= conn.prepareStatement (sql);
           pst.setString(1,jTextField1.getText());
           pst.execute();
             JOptionPane.showMessageDialog(null, "Deleted");
           
         
           
       }catch(Exception e){
           
           JOptionPane.showMessageDialog(null, e);
       if(d==0){
           
       }
       }finally{
        try{
            rs.close();
            pst.close();
            //conn.close();
               
        }
        catch(Exception e){
            JOptionPane.showMessageDialog (null,e);
        }
               
        }
        Update_table();
    }
    }//GEN-LAST:event_cmd_deleteActionPerformed

    private void cmd_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_updateActionPerformed
        try{
            String value1= jTextField1.getText();
            String value2= jTextField2.getText();
            String value3= jTextField3.getText();
            String value4= jTextField4.getText();
            String value5= jTextField5.getText();
            String value6= jTextField6.getText();
            String value7= jTextField7.getText();
            String value8= jTextField8.getText();
            String value9= jTextField9.getText();
            String value10= jTextField10.getText();
            String value11= jTextField11.getText();
            String value12= jTextField12.getText();
            String value13= cmd_Combobox2.getSelectedItem().toString();
            String value14= ((JTextField)txt_Date.getDateEditor().getUiComponent()).getText();
            
            
            
            
            String sql="update `fitness247`.`club members` set `Member ID`='"+value1+"',`Access Key Number`='"+value2+"',"
                    + "`First Name`='"+value3+"',`Last Name`='"+value4+"',`Street Address`='"+value5+"',`City`='"+value6+"',`State`='"+value7+"',"
                    + "`Postal Code`='"+value8+"',`Email`='"+value9+"',`Home Number`='"+value10+"',`Work Number`='"+value11+"',"
                    + "`Mobile Number`='"+value12+"',`Billing Type`='"+value13+"',`Date Joined`='"+value14+"' where `club members`.`Member ID`='"+value1+"'";
            pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Updated");
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
            
            
        }finally{
        try{
            rs.close();
            pst.close();
            //conn.close();
               
        }
        catch(Exception e){
            JOptionPane.showMessageDialog (null,e);
        }
        }
        try{
            String value1= jTextField1.getText();
            String value2= jTextField2.getText();
            String value3= jTextField3.getText();
            String value4= jTextField4.getText();
            String value5= jTextField5.getText();
            String value6= jTextField6.getText();
            String value7= jTextField7.getText();
            String value8= jTextField8.getText();
            String value9= jTextField9.getText();
            String value10= jTextField10.getText();
            String value11= jTextField11.getText();
            String value12= jTextField12.getText();
            String value13= cmd_Combobox2.getSelectedItem().toString();
            String value14= ((JTextField)txt_Date.getDateEditor().getUiComponent()).getText();
            
            
            
            
            String sql="update `fitness247`.`prior members` set `Member ID`='"+value1+"',`Access Key Number`='"+value2+"',"
                    + "`First Name`='"+value3+"',`Last Name`='"+value4+"',`Street Address`='"+value5+"',`City`='"+value6+"',`State`='"+value7+"',"
                    + "`Postal Code`='"+value8+"',`Email`='"+value9+"',`Home Number`='"+value10+"',`Work Number`='"+value11+"',"
                    + "`Mobile Number`='"+value12+"',`Billing Type`='"+value13+"',`Date Joined`='"+value14+"' where `prior members`.`Member ID`='"+value1+"'";
            pst=conn.prepareStatement(sql);
            pst.execute();
            
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
            
            
        }finally{
        try{
            rs.close();
            pst.close();
            //conn.close();
               
        }
        catch(Exception e){
            JOptionPane.showMessageDialog (null,e);
        }       
        
         Update_table();
        } 
    }//GEN-LAST:event_cmd_updateActionPerformed

    private void txt_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyReleased
        try{
        
            String sql ="select * from `fitness247`.`club members` where `club members`.`Last Name` =?";
            pst=conn.prepareStatement (sql);
            pst.setString(1, txt_search.getText());
            rs=pst.executeQuery();
            if(rs.next()){
                
                 String add1 =rs.getString("Member ID");
                 jTextField1.setText(add1);
                 String add2 =rs.getString("Access Key Number");
                 jTextField2.setText(add2);
                 String add3 =rs.getString("First Name");
                 jTextField3.setText(add3);
                 String add4 =rs.getString("Last Name");
                 jTextField4.setText(add4);
                 String add5 =rs.getString("Street Address");
                 jTextField5.setText(add5);
                 String add6 =rs.getString("City");
                 jTextField6.setText(add6);
                 String add7 =rs.getString("State");
                 jTextField7.setText(add7);
                 String add8 =rs.getString("Postal Code");
                 jTextField8.setText(add8);
                 String add9 =rs.getString("Email");
                 jTextField9.setText(add9);
                 String add10 =rs.getString("Home Number");
                 jTextField10.setText(add10);
                 String add11 =rs.getString("Work Number");
                 jTextField11.setText(add11);
                 String add12 =rs.getString("Mobile Number");
                 jTextField12.setText(add12);
                 String add13 =rs.getString("Billing Type");
                 txt_billingtype.setText(add13);
                 String add14 =rs.getString("Date Joined");
                 ((JTextField)txt_Date.getDateEditor().getUiComponent()).setText(add14);
                 
            }
          
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
            
        }
        try{
        
            String sql ="select * from `fitness247`.`club members` where `club members`.`First Name` =?";
            pst=conn.prepareStatement (sql);
            pst.setString(1, txt_search.getText());
            rs=pst.executeQuery();
            if(rs.next()){
                
                 String add1 =rs.getString("Member ID");
                 jTextField1.setText(add1);
                 String add2 =rs.getString("Access Key Number");
                 jTextField2.setText(add2);
                 String add3 =rs.getString("First Name");
                 jTextField3.setText(add3);
                 String add4 =rs.getString("Last Name");
                 jTextField4.setText(add4);
                 String add5 =rs.getString("Street Address");
                 jTextField5.setText(add5);
                 String add6 =rs.getString("City");
                 jTextField6.setText(add6);
                 String add7 =rs.getString("State");
                 jTextField7.setText(add7);
                 String add8 =rs.getString("Postal Code");
                 jTextField8.setText(add8);
                 String add9 =rs.getString("Email");
                 jTextField9.setText(add9);
                 String add10 =rs.getString("Home Number");
                 jTextField10.setText(add10);
                 String add11 =rs.getString("Work Number");
                 jTextField11.setText(add11);
                 String add12 =rs.getString("Mobile Number");
                 jTextField12.setText(add12);
                 String add13 =rs.getString("Billing Type");
                 txt_billingtype.setText(add13);
                 String add14 =rs.getString("Date Joined");
                 ((JTextField)txt_Date.getDateEditor().getUiComponent()).setText(add14);
                 
            }
          
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
            
        }
        try{
        
            String sql ="select * from `fitness247`.`club members` where `club members`.`Access Key Number` =?";
            pst=conn.prepareStatement (sql);
            pst.setString(1, txt_search.getText());
            rs=pst.executeQuery();
            if(rs.next()){
                
                 String add1 =rs.getString("Member ID");
                 jTextField1.setText(add1);
                 String add2 =rs.getString("Access Key Number");
                 jTextField2.setText(add2);
                 String add3 =rs.getString("First Name");
                 jTextField3.setText(add3);
                 String add4 =rs.getString("Last Name");
                 jTextField4.setText(add4);
                 String add5 =rs.getString("Street Address");
                 jTextField5.setText(add5);
                 String add6 =rs.getString("City");
                 jTextField6.setText(add6);
                 String add7 =rs.getString("State");
                 jTextField7.setText(add7);
                 String add8 =rs.getString("Postal Code");
                 jTextField8.setText(add8);
                 String add9 =rs.getString("Email");
                 jTextField9.setText(add9);
                 String add10 =rs.getString("Home Number");
                 jTextField10.setText(add10);
                 String add11 =rs.getString("Work Number");
                 jTextField11.setText(add11);
                 String add12 =rs.getString("Mobile Number");
                 jTextField12.setText(add12);
                 String add13 =rs.getString("Billing Type");
                 txt_billingtype.setText(add13);
                 String add14 =rs.getString("Date Joined");
                 ((JTextField)txt_Date.getDateEditor().getUiComponent()).setText(add14);
                 
            }
          
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
            
        }
        finally{
        try{
            rs.close();
            pst.close();
            //conn.close();
               
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
               
        }
    }//GEN-LAST:event_txt_searchKeyReleased

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        try{
            Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler "+"C:\\FREQUENTLY ASKED QUESTIONS.docx");
            
           
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
      
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        int p= JOptionPane.showConfirmDialog(null, "Are you sure you want to Exit?","Exit", JOptionPane.YES_NO_OPTION);
        if(p==0){
        System.exit(0);
        }
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void cmd_printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_printActionPerformed
       
        MessageFormat header = new MessageFormat("Club Members Report");
        MessageFormat footer = new MessageFormat("Page {0,number,integer}");
        try{
            Table_ClubMembers.print(JTable.PrintMode.NORMAL, header, footer);
            
            
        }catch(java.awt.print.PrinterException e){
            System.err.format("Can Not Print %s%n", e.getMessage());
            
        }
    }//GEN-LAST:event_cmd_printActionPerformed

    private void cmd_ComboboxPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cmd_ComboboxPopupMenuWillBecomeInvisible
        ComboSelect();
    }//GEN-LAST:event_cmd_ComboboxPopupMenuWillBecomeInvisible

    private void Table_ClubMembersKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Table_ClubMembersKeyReleased
        if(evt.getKeyCode()==KeyEvent.VK_DOWN || evt.getKeyCode()==KeyEvent.VK_UP){
           
         try{
            int row =Table_ClubMembers.getSelectedRow();
            String Table_click=(Table_ClubMembers.getModel().getValueAt(row, 0).toString());
            String sql = ("select * from `fitness247`.`club members` where `club members`.`Member ID` = '"+Table_click+"' ");
            pst=conn.prepareStatement (sql);
            rs=pst.executeQuery();
            if (rs.next()){
            
            String add1 =rs.getString("Member ID");
            jTextField1.setText(add1);
            String add2 =rs.getString("Access Key Number");
            jTextField2.setText(add2);
            String add3 =rs.getString("First Name");
            jTextField3.setText(add3);
            String add4 =rs.getString("Last Name");
            jTextField4.setText(add4);
            String add5 =rs.getString("Street Address");
            jTextField5.setText(add5);
            String add6 =rs.getString("City");
            jTextField6.setText(add6);
            String add7 =rs.getString("State");
            jTextField7.setText(add7);
            String add8 =rs.getString("Postal Code");
            jTextField8.setText(add8);
            String add9 =rs.getString("Email");
            jTextField9.setText(add9);
            String add10 =rs.getString("Home Number");
            jTextField10.setText(add10);
            String add11 =rs.getString("Work Number");
            jTextField11.setText(add11);
            String add12 =rs.getString("Mobile Number");
            jTextField12.setText(add12);
            String add13 =rs.getString("Billing Type");
            txt_billingtype.setText(add13);
            String add14 =rs.getString("Date Joined");
            ((JTextField)txt_Date.getDateEditor().getUiComponent()).setText(add14);
            } 
        }catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        
              
        
        }finally{
        try{
            rs.close();
            pst.close();
            //conn.close();
               
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
               
        }
    }                                   
           
           
           
    }//GEN-LAST:event_Table_ClubMembersKeyReleased

    private void cmd_openWebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_openWebActionPerformed
        try{
            String URL ="https://www.google.com/";
            java.awt.Desktop.getDesktop().browse(java.net.URI.create(URL));

        }catch (Exception e){
            JOptionPane.showMessageDialog (null, e);

        }
    }//GEN-LAST:event_cmd_openWebActionPerformed

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        char c =evt.getKeyChar();
        if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE)|| c==KeyEvent.VK_DELETE)){
            getToolkit().beep();
            evt.consume();
        
        
        }
    }//GEN-LAST:event_jTextField1KeyTyped

    private void jTextField2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyTyped
        char c =evt.getKeyChar();
        if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE)|| c==KeyEvent.VK_DELETE)){
            getToolkit().beep();
            evt.consume();
        
        
        }
    }//GEN-LAST:event_jTextField2KeyTyped

    private void jTextField8KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField8KeyTyped
        char c =evt.getKeyChar();
        if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE)|| c==KeyEvent.VK_DELETE)){
            getToolkit().beep();
            evt.consume();
        
        
        }
    }//GEN-LAST:event_jTextField8KeyTyped

    private void jTextField10KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField10KeyTyped
        char c =evt.getKeyChar();
        if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE)|| c==KeyEvent.VK_DELETE)){
            getToolkit().beep();
            evt.consume();
        
        
        }
    }//GEN-LAST:event_jTextField10KeyTyped

    private void jTextField11KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField11KeyTyped
        char c =evt.getKeyChar();
        if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE)|| c==KeyEvent.VK_DELETE)){
            getToolkit().beep();
            evt.consume();
        
        
        }
    }//GEN-LAST:event_jTextField11KeyTyped

    private void jTextField12KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField12KeyTyped
        char c =evt.getKeyChar();
        if(!(Character.isDigit(c) || (c==KeyEvent.VK_BACK_SPACE)|| c==KeyEvent.VK_DELETE)){
            getToolkit().beep();
            evt.consume();
        
        
        }
    }//GEN-LAST:event_jTextField12KeyTyped

    private void cmd_CalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_CalculateActionPerformed
        try{
            String sql="select count(*) from `fitness247`.`club members`";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next()){
                String sum=rs.getString("count(*)");
                txt_count.setText(sum);
            
            }
             
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
           
        }finally{
        try{
            rs.close();
            pst.close();
            //conn.close();
               
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
               
        }
        Update_table();
    }//GEN-LAST:event_cmd_CalculateActionPerformed

    private void cmd_SortLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_SortLastNameActionPerformed
        try{
    String sql ="Select * from `fitness247`.`club members` order by `Last Name`";
    pst=conn.prepareStatement (sql);
    rs=pst.executeQuery();
    Table_ClubMembers.setModel(DbUtils.resultSetToTableModel(rs));
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
    }finally{
        try{
            rs.close();
            pst.close();
            //conn.close();
               
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
               
        }
    }//GEN-LAST:event_cmd_SortLastNameActionPerformed

    private void cmd_SortBillingTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_SortBillingTypeActionPerformed
        try{
    String sql ="Select * from `fitness247`.`club members` order by `Billing Type`";
    pst=conn.prepareStatement (sql);
    rs=pst.executeQuery();
    Table_ClubMembers.setModel(DbUtils.resultSetToTableModel(rs));
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
    }finally{
        try{
            rs.close();
            pst.close();
            //conn.close();
               
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
               
        }
    }//GEN-LAST:event_cmd_SortBillingTypeActionPerformed

    private void cmd_UpdateTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_UpdateTableActionPerformed
        Update_table();
    }//GEN-LAST:event_cmd_UpdateTableActionPerformed
   
   

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }/*UIManager.setLookAndFeel("com.jtattoo.plaf.acryl.AcrylLookAndFeel"); CAN be used to change LookandFeel*/
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Club_Member.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Club_Member.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Club_Member.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Club_Member.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Club_Member().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table_ClubMembers;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cmd_Calculate;
    private javax.swing.JComboBox cmd_Combobox;
    private javax.swing.JComboBox cmd_Combobox2;
    private javax.swing.JRadioButton cmd_SortBillingType;
    private javax.swing.JRadioButton cmd_SortLastName;
    private javax.swing.JButton cmd_UpdateTable;
    private javax.swing.JButton cmd_clear;
    private javax.swing.JButton cmd_delete;
    private javax.swing.JButton cmd_exit;
    private javax.swing.JButton cmd_openWeb;
    private javax.swing.JButton cmd_print;
    private javax.swing.JButton cmd_save;
    private javax.swing.JButton cmd_update;
    private javax.swing.JMenu date_txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JMenu time_txt;
    private com.toedter.calendar.JDateChooser txt_Date;
    private javax.swing.JTextField txt_billingtype;
    private javax.swing.JTextField txt_count;
    private javax.swing.JTextField txt_search;
    // End of variables declaration//GEN-END:variables
    
    
}
